spring:
  #thymeleaf配置
  thymeleaf:
    # 关闭缓存
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: hjj123456
    hikari:
      #连接池名字
      pool-name: DateHikariCP
      #最小连接数
      minimum-idle: 5
      # 连接存在时间 600000=>10分钟
      idle-timeout: 1800000
      # 最大连接数 默认为10
      maximum-pool-size: 10
      # ?????????????
      auto-commit: true
      # ???????? 0??????????1800000=>30??
      max-lifetime: 1800000
      # ??????????3000=>30?
      connection-timeout: 3000
      # ???????????
      connection-test-query: SELECT 1
  redis:
    #服务器地址
    #端口
    host: 127.0.0.1
    port: 6379
    #默认操作数据库 0
    database: 0
    #超时时间
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 8
        #最大阻塞等待时间，默认-1ms
        max-wait: 10000ms
        #最大空闲连接，默认8
        max-idle: 200
        #最小空闲连接，默认0
        min-idle: 5



#Mybatis-plus
mybatis-plus:
  #配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置Mybatis数据返回类型别名（默认别名为类名）
  type-aliases-package: com.han.seckill.pojo

#Mybatis SQL打印（方法接口所在的包，不是Mapper.xml所在的包）
logging:
  level:
    com.xxx.seckill.mapper: debug
